[project]
name = "vocabio"
version = "0.1.0"
description = "A personal vocabulary project for learning and organising English words"
authors = [
    { name = "Alex", email = "alex.nuclearboy@gmail.com" },
]
license = "Apache-2.0"
readme = "README.md"
dynamic = ["dependencies"]

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0.7"
python-dotenv = "^1.2.2"
psycopg = { extras = ["binary"], version = "^3.3.4" }
dj-database-url = "^3.1.2"
gunicorn = "^26.0.0"
whitenoise = "^6.12.0"
colorlog = "^6.12.0"
django-axes = ">=8.3.1,<9"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pylint = "^4.0.6"
pylint-django = "^2.8.0"

[tool.pylint.main]
load-plugins = ["pylint_django"]
django-settings-module = "config.settings"
ignore = ["migrations"]
jobs = 0

[tool.pylint.format]
max-line-length = 79

[tool.pylint.similarities]
min-similarity-lines = 10

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
