# Generated by Django 6.0.7 on 2026-08-03 13:54

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAccess',
            fields=[
            ],
            options={
                'verbose_name': 'application access',
                'verbose_name_plural': 'application access',
                'permissions': [('access_application', 'Can access the application')],
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
